# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dov0yuGKe1hwr3LVIwoJTM8OBoLo73uUqLsDw5FQcmg=,iv:oKM2MR19HYSzXqZBlBAfzYwqgFdY3yKOs1FAgRc1qes=,tag:/nwckaTYvwQ0KjfAWwiWPg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dlsaw4anajxrwmyr6r23uwluvj49ph8zlwrnrds2pw4lvvgcuc5qjy9zek
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkZmREhaUFI3K1dzNWZk
        S24wMlRRakFXS2V0L09MeGZpVnhTZFhnRVVJCjFnU1JKWXgrZ0M0TjJmUTNOQis2
        Ynd0STA3Sm9iZ0VIeTVHYXlVRkhvMGsKLS0tIGd2RkNPUzhxUlBCSDBzdmVEc1Fk
        emg3ZTRENjlQU0lFOG1pY0ZCcC9JeE0KhaO6KDc2UWZogQ0ZjOAAQ+T6RHclbV5c
        w/cYTCw84fbsSNa24wgj6RdHp2wbd8vm9oc6sYSvvhzmQECL4CEDXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:13:20Z"
  mac: ENC[AES256_GCM,data:i2f1H0dvL4clVsRBE+WEV+5dUqDcSZILZyCZVo8bWr8RAHYvCcklXiOzw7G2T1RzEyIJIvZumEV5+VqBqcIEURPp7scM1FRSFZwe1LJiqe7F1wZavRwqa+M0z0OMCiHP5lFMVbM8nCYbMcjZWkwxR7HBpRPxzbRKzqKSXAsQ63A=,iv:38Z/uN2g+CAKzaob4cUDTVhVf+iFQ8nJtGhd/RqoPcQ=,tag:pLz7QdJBiwD2rcEwGw0I6g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
