# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:84kozqukQc87im4YhcaXbx8gOqGmLossTdsd3AgwK1437IrlIm3ttg==,iv:1J68LxwrXB8td4PhjOCgjA7s2yBN6kQTitug3RmquHE=,tag:5MmEeciNfCt5p0GUAQyX4g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dlsaw4anajxrwmyr6r23uwluvj49ph8zlwrnrds2pw4lvvgcuc5qjy9zek
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bnh2WkhHUHd6ZjAwMDdk
        L2xMZFZ5K2M0WGFTZmV1bVErMGJUbFgwYm1ZCmtEazNueTY5YjVoNlZQTHVlbk15
        MUZhZFJUdmM2OTVkZkxjbEFpbXlZU1kKLS0tICtjVHVMK1NWN1c3MHRYdVlhanhF
        RkFZRFMxTFdvMGJrMVRHcVVFSENsMlUK86oQywsBsHKBecRzk++DQXiV5kuNci/D
        tOfwqRG6wNXziQX6WcXFdiexEuH/uysc0AhVRrOtynK5ElT6RaijiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:13:20Z"
  mac: ENC[AES256_GCM,data:C2uBJMV1zUc5JowZJL9oK6RIXCvTEi6X7tRFko0PBevx58uyAoL8Bvii1D2xmkK60h7/QfGFgbUe4Td65eMSTqS7dyVPz+09pg3UrHSR6t7uC4Xuu3XV9eepOn3YEP3JDAJYu30osWOlUe4fVZTRRlGAc2f+ir0moBB6p72/eYQ=,iv:ASzXXyF1UzIErluLvgTDr55OdxIWO5PdmSajgv89Kcc=,tag:bOVDQjkBf/OjCmvGuXm/IQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
