# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.2

clusterName: main
endpoint: https://10.1.135.100:6443

clusterPodNets:
  - "172.21.0.0/16"
clusterSvcNets:
  - "172.22.0.0/16"

additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.1.135.100"
  - "k8s.astrateam.net"
additionalMachineCertSans: *sans

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ivn-k8s-mng01"
    ipAddress: "10.1.135.31"
    installDiskSelector:
      serial: "S78GNL0X982000V"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:c3:85:b7"
        dhcp: false
        addresses:
          - "10.1.135.31/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500
        vip:
          ip: "10.1.135.100"

      - deviceSelector:
          hardwareAddr: "bc:24:11:79:25:58"
        dhcp: false
        addresses:
          - "10.1.115.31/24"
        mtu: 9000

  - hostname: "ivn-k8s-mng02"
    ipAddress: "10.1.135.32"
    installDiskSelector:
      serial: "S78GNL0X534609D"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:3e:a1:e1"
        dhcp: false
        addresses:
          - "10.1.135.32/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500
        vip:
          ip: "10.1.135.100"

      - deviceSelector:
          hardwareAddr: "bc:24:11:bc:bc:3d"
        dhcp: false
        addresses:
          - "10.1.115.32/24"
        mtu: 9000

  - hostname: "ivn-k8s-mng03"
    ipAddress: "10.1.135.33"
    installDiskSelector:
      serial: "S78GNL0X534599X"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a8:f3:0b"
        dhcp: false
        addresses:
          - "10.1.135.33/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500
        vip:
          ip: "10.1.135.100"

      - deviceSelector:
          hardwareAddr: "bc:24:11:eb:88:af"
        dhcp: false
        addresses:
          - "10.1.115.33/24"
        mtu: 9000

  - hostname: "ivn-k8s-wrk01"
    ipAddress: "10.1.135.41"
    installDiskSelector:
      serial: "S78GNL0X981951V"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:87:77:55"
        dhcp: false
        addresses:
          - "10.1.135.41/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500

      - deviceSelector:
          hardwareAddr: "bc:24:11:5f:e3:6a"
        dhcp: false
        addresses:
          - "10.1.115.41/24"
        mtu: 9000

  - hostname: "ivn-k8s-wrk02"
    ipAddress: "10.1.135.42"
    installDiskSelector:
      serial: "S78GNL0X500319H"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:bf:a0:aa"
        dhcp: false
        addresses:
          - "10.1.135.42/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500

      - deviceSelector:
          hardwareAddr: "bc:24:11:e9:31:93"
        dhcp: false
        addresses:
          - "10.1.115.42/24"
        mtu: 9000

  - hostname: "ivn-k8s-wrk03"
    ipAddress: "10.1.135.43"
    installDiskSelector:
      serial: "S78GNL0X981946A"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c2baa8b20c90c3547024a59bb3fd8804749d27209bd7d516a01740fa538c4d49
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9c:19:40"
        dhcp: false
        addresses:
          - "10.1.135.43/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.135.1"
        mtu: 1500

      - deviceSelector:
          hardwareAddr: "bc:24:11:8c:9b:c1"
        dhcp: false
        addresses:
          - "10.1.115.43/24"
        mtu: 9000


# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

